import { addDoc, collection } from "firebase/firestore";
import { db } from "../firebase_Config";

// 50 NOUVELLES ACTIVITÉS ULTRA VARIÉES POUR BRUXELLES
const MORE_ACTIVITIES_DATA = [
  // 🍽️ FOOD & DRINK (15 activités)
  {
    title: "Atelier Cuisine Italienne chez Cucina",
    description: "Apprenez à faire des pâtes fraîches et tiramisu avec un chef italien ! Dégustation incluse, ambiance conviviale.",
    category: "Food",
    price: "Payant",
    location: "Ixelles",
    interests: ["cuisine", "apprendre", "italie"],
    image: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=800&q=80",
    isNew: true,
    website: "https://www.cucinabrussels.be",
    hours: "Sam: 14:00-17:00",
    rating: 4.6,
  },
  {
    title: "Brunch au Plattesteen",
    description: "Brunch légendaire de Bruxelles ! Buffet à volonté, ambiance cosy, réservation obligatoire. Le meilleur de la ville !",
    category: "Food",
    price: "Payant",
    location: "Bruxelles - Centre",
    interests: ["food", "brunch", "convivial"],
    image: "https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?w=800&q=80",
    isNew: false,
    website: "https://www.plattesteen.be",
    hours: "Dim: 10:00-15:00",
    rating: 4.7,
  },
  {
    title: "Dégustation de Chocolat chez Pierre Marcolini",
    description: "Visite de l'atelier + dégustation de chocolats belges d'exception. Découvrez les secrets du chocolatier star !",
    category: "Food",
    price: "Payant",
    location: "Sablon",
    interests: ["chocolat", "dégustation", "belgique"],
    image: "https://images.unsplash.com/photo-1511381939415-e44015466834?w=800&q=80",
    isNew: false,
    website: "https://www.marcolini.com",
    hours: "Sam: 11:00-12:30",
    rating: 4.8,
  },
  {
    title: "Atelier Brassage de Bière",
    description: "Brassez votre propre bière belge ! Atelier de 3h avec un brasseur pro, repartez avec vos bouteilles.",
    category: "Food",
    price: "Payant",
    location: "Anderlecht",
    interests: ["bière", "artisanat", "apprendre"],
    image: "https://images.unsplash.com/photo-1608270586620-248524c67de9?w=800&q=80",
    isNew: true,
    website: "https://www.beerworkshop.be",
    hours: "Sam: 14:00-17:00",
    rating: 4.5,
  },
  {
    title: "Food Tour dans les Marolles",
    description: "Visite guidée gourmande ! Frites, gaufres, bières, fromages... Découvrez les meilleures adresses du quartier.",
    category: "Food",
    price: "Payant",
    location: "Bruxelles - Marolles",
    interests: ["food", "découverte", "balade"],
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80",
    isNew: false,
    website: "https://www.brusselsfoodtours.com",
    hours: "Sam-Dim: 11:00-14:00",
    rating: 4.4,
  },
  {
    title: "Cours de Cocktails au Spirito",
    description: "Apprenez à faire 3 cocktails signature avec un mixologue pro ! Bar magnifique dans une ancienne église.",
    category: "Food",
    price: "Payant",
    location: "Bruxelles - Centre",
    interests: ["cocktails", "apprendre", "soirée"],
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800&q=80",
    isNew: false,
    website: "https://www.spirito.be",
    hours: "Jeu: 19:00-21:00",
    rating: 4.6,
  },
  {
    title: "Atelier Sushi chez Yuki",
    description: "Maîtrisez l'art du sushi avec un chef japonais ! Technique, dégustation, ambiance zen. Max 10 personnes.",
    category: "Food",
    price: "Payant",
    location: "Saint-Gilles",
    interests: ["cuisine", "japon", "sushi"],
    image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800&q=80",
    isNew: true,
    website: "https://www.yukisushi.be",
    hours: "Ven: 18:00-21:00",
    rating: 4.7,
  },
  {
    title: "Dégustation de Fromages Belges",
    description: "Tour de Belgique fromager ! 8 fromages artisanaux avec vins belges. Animé par un affineur passionné.",
    category: "Food",
    price: "Payant",
    location: "Ixelles",
    interests: ["fromage", "dégustation", "belgique"],
    image: "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=800&q=80",
    isNew: false,
    website: "https://www.fromagerie.be",
    hours: "Ven: 19:00-21:00",
    rating: 4.5,
  },
  {
    title: "Pâtisserie Française chez Mamy Louise",
    description: "Atelier pâtisserie : éclairs, macarons, tartes ! Techniques pro, recettes à emporter.",
    category: "Food",
    price: "Payant",
    location: "Uccle",
    interests: ["pâtisserie", "apprendre", "gourmandise"],
    image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&q=80",
    isNew: false,
    website: "https://www.mamylouise.be",
    hours: "Sam: 10:00-13:00",
    rating: 4.8,
  },
  {
    title: "Marché Fermier de Flagey",
    description: "Marché de producteurs locaux tous les dimanches ! Légumes bio, fromages, viandes, pains artisanaux.",
    category: "Food",
    price: "Gratuit",
    location: "Ixelles - Flagey",
    interests: ["marché", "bio", "local"],
    image: "https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800&q=80",
    isNew: false,
    website: "https://www.marchebioflagey.be",
    hours: "Dim: 08:00-14:00",
    rating: 4.3,
  },
  {
    title: "Cours de Pâtes Fraîches",
    description: "De la farine aux raviolis ! Apprenez 3 types de pâtes italiennes. Dégustation et verre de vin offert.",
    category: "Food",
    price: "Payant",
    location: "Saint-Gilles",
    interests: ["cuisine", "italie", "pâtes"],
    image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&q=80",
    isNew: true,
    website: "https://www.pastacooking.be",
    hours: "Mer: 18:30-21:00",
    rating: 4.7,
  },
  {
    title: "Balade & Bières Artisanales",
    description: "Tour guidé de 3 microbrasseries bruxelloises ! Rencontrez les brasseurs, dégustez, apprenez l'histoire.",
    category: "Food",
    price: "Payant",
    location: "Bruxelles - Divers quartiers",
    interests: ["bière", "découverte", "artisan"],
    image: "https://images.unsplash.com/photo-1532634993-15f421e42ec0?w=800&q=80",
    isNew: false,
    website: "https://www.beerwalks.be",
    hours: "Sam: 15:00-19:00",
    rating: 4.6,
  },
  {
    title: "Atelier Viennoiseries au MOF",
    description: "Croissants, pains au chocolat, brioches avec un Meilleur Ouvrier de France ! Niveau débutant ok.",
    category: "Food",
    price: "Payant",
    location: "Woluwe",
    interests: ["boulangerie", "apprendre", "france"],
    image: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=800&q=80",
    isNew: true,
    website: "https://www.atelierboulanger.be",
    hours: "Dim: 09:00-12:00",
    rating: 4.9,
  },
  {
    title: "Dégustation de Gins Belges",
    description: "7 gins artisanaux belges à découvrir ! Histoire, botaniques, perfect serve. Bar cosy, snacks inclus.",
    category: "Food",
    price: "Payant",
    location: "Ixelles",
    interests: ["gin", "dégustation", "belgique"],
    image: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=800&q=80",
    isNew: false,
    website: "https://www.ginbar.be",
    hours: "Ven: 20:00-22:00",
    rating: 4.4,
  },
  {
    title: "Brunch Végétarien au Green Lab",
    description: "Brunch 100% veggie et local ! Bowls, smoothies, pâtisseries maison. Ambiance healthy et instagrammable.",
    category: "Food",
    price: "Payant",
    location: "Saint-Gilles",
    interests: ["food", "végé", "healthy"],
    image: "https://images.unsplash.com/photo-1511690656952-34342bb7c2f2?w=800&q=80",
    isNew: true,
    website: "https://www.greenlab.be",
    hours: "Sam-Dim: 10:00-15:00",
    rating: 4.5,
  },

  // 🎨 WORKSHOPS CRÉATIFS (12 activités)
  {
    title: "Atelier Poterie chez Argile",
    description: "Initiez-vous au tour de potier ! Créez bol, vase ou tasse. Cuisson incluse, récupérez votre création 2 semaines après.",
    category: "Atelier",
    price: "Payant",
    location: "Ixelles",
    interests: ["poterie", "créativité", "manuel"],
    image: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800&q=80",
    isNew: true,
    website: "https://www.argilebrussels.be",
    hours: "Mer-Sam: 14:00-17:00",
    rating: 4.7,
  },
  {
    title: "Cours de Couture pour Débutants",
    description: "Apprenez les bases : machine, patron, première création (tote bag ou pochette). 4 séances, max 8 personnes.",
    category: "Atelier",
    price: "Payant",
    location: "Saint-Gilles",
    interests: ["couture", "diy", "mode"],
    image: "https://images.unsplash.com/photo-1556906681-d79935c93146?w=800&q=80",
    isNew: false,
    website: "https://www.ateliercouture.be",
    hours: "Jeu: 18:00-20:00",
    rating: 4.5,
  },
  {
    title: "Atelier Fabrication de Bougies",
    description: "Créez vos bougies parfumées ! Choix de senteurs, couleurs, moules. Repartez avec 3 bougies artisanales.",
    category: "Atelier",
    price: "Payant",
    location: "Etterbeek",
    interests: ["diy", "créativité", "déco"],
    image: "https://images.unsplash.com/photo-1602874801006-e2c9e791c85b?w=800&q=80",
    isNew: true,
    website: "https://www.candleworkshop.be",
    hours: "Sam: 14:00-16:00",
    rating: 4.6,
  },
  {
    title: "Atelier Macramé Mural",
    description: "Réalisez votre suspension murale en macramé ! Technique, design, matériel fourni. Déco bohème garantie.",
    category: "Atelier",
    price: "Payant",
    location: "Ixelles",
    interests: ["macramé", "diy", "déco"],
    image: "https://images.unsplash.com/photo-1619378951629-774c5c5cf644?w=800&q=80",
    isNew: false,
    website: "https://www.macrameworkshop.be",
    hours: "Dim: 13:00-16:00",
    rating: 4.4,
  },
  {
    title: "Cours de Dessin au Musée",
    description: "Dessinez dans les salles du musée ! Techniques de croquis, perspective, ombres. Tous niveaux acceptés.",
    category: "Atelier",
    price: "Payant",
    location: "Bruxelles - Musées Royaux",
    interests: ["dessin", "art", "apprendre"],
    image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&q=80",
    isNew: false,
    website: "https://www.fine-arts-museum.be",
    hours: "Sam: 10:00-12:00",
    rating: 4.3,
  },
  {
    title: "Atelier Terrarium DIY",
    description: "Créez votre mini-écosystème sous verre ! Plantes, mousse, déco. Entretien facile, idéal débutants.",
    category: "Atelier",
    price: "Payant",
    location: "Saint-Gilles",
    interests: ["plantes", "diy", "nature"],
    image: "https://images.unsplash.com/photo-1545239705-1564e58b9e4a?w=800&q=80",
    isNew: true,
    website: "https://www.terrariumlab.be",
    hours: "Dim: 15:00-17:00",
    rating: 4.6,
  },
  {
    title: "Atelier Bijoux en Argent",
    description: "Fabriquez votre bague ou bracelet en argent 925 ! Techniques d'orfèvre, finition pro, repartez avec votre création.",
    category: "Atelier",
    price: "Payant",
    location: "Bruxelles - Centre",
    interests: ["bijoux", "artisanat", "créativité"],
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&q=80",
    isNew: false,
    website: "https://www.silverworkshop.be",
    hours: "Sam: 14:00-18:00",
    rating: 4.8,
  },
  {
    title: "Cours de Calligraphie Moderne",
    description: "Maîtrisez le brush lettering ! Techniques, composition, projets. Matériel fourni, 3 sessions.",
    category: "Atelier",
    price: "Payant",
    location: "Ixelles",
    interests: ["calligraphie", "art", "lettrage"],
    image: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=800&q=80",
    isNew: true,
    website: "https://www.calligraphylab.be",
    hours: "Mer: 18:30-20:30",
    rating: 4.5,
  },
  {
    title: "Atelier Réparation de Vélo",
    description: "Apprenez à entretenir votre vélo ! Crevaison, freins, vitesses. Atelier associatif, ambiance conviviale.",
    category: "Atelier",
    price: "Gratuit",
    location: "Ixelles",
    interests: ["vélo", "diy", "écologie"],
    image: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=800&q=80",
    isNew: false,
    website: "https://www.cyclo.org",
    hours: "Mar-Jeu: 18:00-21:00",
    rating: 4.4,
  },
  {
    title: "Atelier Upcycling Textile",
    description: "Transformez vieux vêtements en pièces uniques ! Techniques de customisation, zéro déchet, mode éco-responsable.",
    category: "Atelier",
    price: "Payant",
    location: "Anderlecht",
    interests: ["mode", "écologie", "diy"],
    image: "https://images.unsplash.com/photo-1558769132-cb1aea3c8565?w=800&q=80",
    isNew: true,
    website: "https://www.upcyclinglab.be",
    hours: "Sam: 14:00-17:00",
    rating: 4.6,
  },
  {
    title: "Atelier Fleurs Séchées",
    description: "Créez votre bouquet de fleurs séchées ! Techniques de séchage, composition, style bohème. Matériel fourni.",
    category: "Atelier",
    price: "Payant",
    location: "Uccle",
    interests: ["fleurs", "déco", "créativité"],
    image: "https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?w=800&q=80",
    isNew: false,
    website: "https://www.driedflowers.be",
    hours: "Dim: 14:00-16:00",
    rating: 4.7,
  },
  {
    title: "Cours de Linogravure",
    description: "Initiez-vous à la gravure sur lino ! Dessin, sculpture, impression. Créez vos propres estampes à emporter.",
    category: "Atelier",
    price: "Payant",
    location: "Saint-Gilles",
    interests: ["art", "gravure", "impression"],
    image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=800&q=80",
    isNew: true,
    website: "https://www.printlab.be",
    hours: "Ven: 18:00-21:00",
    rating: 4.5,
  },

  // 💆 BIEN-ÊTRE (8 activités)
  {
    title: "Yoga au Parc du Cinquantenaire",
    description: "Cours de yoga gratuit en plein air tous les dimanches ! Tous niveaux, ambiance zen, tapis à apporter.",
    category: "Bien-être",
    price: "Gratuit",
    location: "Etterbeek - Parc du Cinquantenaire",
    interests: ["yoga", "nature", "sport"],
    image: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&q=80",
    isNew: false,
    website: "https://www.yogapark.be",
    hours: "Dim: 10:00-11:00",
    rating: 4.5,
  },
  {
    title: "Hammam & Spa Orientica",
    description: "Expérience hammam authentique ! Gommage, massage, thé à la menthe. 3h de détente totale.",
    category: "Bien-être",
    price: "Payant",
    location: "Ixelles",
    interests: ["spa", "détente", "massage"],
    image: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&q=80",
    isNew: false,
    website: "https://www.orientica.be",
    hours: "Lun-Dim: 10:00-22:00",
    rating: 4.7,
  },
  {
    title: "Méditation Guidée au Shambhala",
    description: "Séances de méditation bouddhiste pour débutants. Techniques de respiration, pleine conscience. Donation libre.",
    category: "Bien-être",
    price: "Gratuit",
    location: "Bruxelles - Centre",
    interests: ["méditation", "zen", "spiritualité"],
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&q=80",
    isNew: false,
    website: "https://www.shambhala.be",
    hours: "Mer: 19:00-20:30",
    rating: 4.6,
  },
  {
    title: "Bain Nordique & Sauna",
    description: "Bains chauds en extérieur + sauna finlandais. Vue sur la nature, ambiance cocooning, max 8 personnes.",
    category: "Bien-être",
    price: "Payant",
    location: "Watermael-Boitsfort",
    interests: ["spa", "détente", "nature"],
    image: "https://images.unsplash.com/photo-1571731956672-f2b94d7dd0cb?w=800&q=80",
    isNew: true,
    website: "https://www.nordicbath.be",
    hours: "Ven-Dim: 14:00-21:00",
    rating: 4.8,
  },
  {
    title: "Cours de Pilates Reformer",
    description: "Pilates sur machine Reformer ! Renforcement musculaire profond, posture, souplesse. Petits groupes.",
    category: "Bien-être",
    price: "Payant",
    location: "Ixelles",
    interests: ["sport", "pilates", "fitness"],
    image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&q=80",
    isNew: false,
    website: "https://www.pilatesstudio.be",
    hours: "Lun-Ven: 07:00-20:00",
    rating: 4.5,
  },
  {
    title: "Atelier Sophrologie Anti-Stress",
    description: "Techniques de relaxation et gestion du stress. Respiration, visualisation, détente musculaire.",
    category: "Bien-être",
    price: "Payant",
    location: "Woluwe",
    interests: ["relaxation", "zen", "santé"],
    image: "https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=800&q=80",
    isNew: true,
    website: "https://www.sophro.be",
    hours: "Sam: 11:00-12:30",
    rating: 4.4,
  },
  {
    title: "Massage Thaï Traditionnel",
    description: "Massage thaïlandais 2h avec thérapeute certifié. Étirements, pressions, huiles essentielles. Pure détente.",
    category: "Bien-être",
    price: "Payant",
    location: "Etterbeek",
    interests: ["massage", "détente", "thaï"],
    image: "https://images.unsplash.com/photo-1519823551278-64ac92734fb1?w=800&q=80",
    isNew: false,
    website: "https://www.thaimassage.be",
    hours: "Lun-Sam: 10:00-20:00",
    rating: 4.7,
  },
  {
    title: "Cours de Yin Yoga",
    description: "Yoga doux et méditatif. Postures tenues longtemps, étirements profonds, relaxation totale. Débutants ok.",
    category: "Bien-être",
    price: "Payant",
    location: "Saint-Gilles",
    interests: ["yoga", "détente", "souplesse"],
    image: "https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?w=800&q=80",
    isNew: false,
    website: "https://www.yinyoga.be",
    hours: "Dim: 18:00-19:30",
    rating: 4.6,
  },

  // 🛍️ SHOPPING & VINTAGE (8 activités)
  {
    title: "Think Twice (Friperie Vintage)",
    description: "Chaîne de friperies avec 5 magasins à Bruxelles ! Vêtements vintage triés, prix abordables, nouveautés chaque semaine.",
    category: "Shopping",
    price: "Gratuit",
    location: "Ixelles / Saint-Gilles / Centre",
    interests: ["vintage", "mode", "shopping"],
    image: "https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?w=800&q=80",
    isNew: false,
    website: "https://www.thinktwice.be",
    hours: "Lun-Sam: 10:00-18:30",
    rating: 4.3,
  },
  {
    title: "Marché aux Antiquités du Sablon",
    description: "Marché d'antiquités et brocante tous les week-ends ! Meubles, art, bijoux vintage, objets rares.",
    category: "Shopping",
    price: "Gratuit",
    location: "Sablon",
    interests: ["antiquité", "vintage", "chine"],
    image: "https://images.unsplash.com/photo-1567401893414-76b7b1e5a7a5?w=800&q=80",
    isNew: false,
    website: "https://www.sablon-antiques.be",
    hours: "Sam-Dim: 09:00-18:00",
    rating: 4.4,
  },
  {
    title: "Les Petits Riens (Seconde Main Solidaire)",
    description: "Magasin solidaire avec mode, déco, livres, vinyles. Prix mini, cause humanitaire. 10 adresses à Bruxelles !",
    category: "Shopping",
    price: "Gratuit",
    location: "Bruxelles - Plusieurs adresses",
    interests: ["seconde main", "solidaire", "shopping"],
    image: "https://images.unsplash.com/photo-1558769132-92e717d613cd?w=800&q=80",
    isNew: false,
    website: "https://www.petitsriens.be",
    hours: "Lun-Sam: 10:00-18:00",
    rating: 4.2,
  },
  {
    title: "Gabriele Vintage (Boutique Haut de Gamme)",
    description: "Vintage de luxe ! Chanel, Hermès, Dior... Pièces authentiques certifiées, expertise mode.",
    category: "Shopping",
    price: "Gratuit",
    location: "Sablon",
    interests: ["luxe", "vintage", "mode"],
    image: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800&q=80",
    isNew: false,
    website: "https://www.gabriele-vintage.com",
    hours: "Mar-Sam: 11:00-18:00",
    rating: 4.6,
  },
  {
    title: "Sterling Books (Librairie Anglaise)",
    description: "Librairie anglophone mythique ! Livres neufs et d'occasion, événements littéraires, café cosy.",
    category: "Shopping",
    price: "Gratuit",
    location: "Uccle - Chaussée de Waterloo",
    interests: ["livres", "anglais", "culture"],
    image: "https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=800&q=80",
    isNew: false,
    website: "https://www.sterlingbooks.be",
    hours: "Lun-Sam: 10:00-18:30",
    rating: 4.5,
  },
  {
    title: "Lieu-Dit Concept Store",
    description: "Concept store design belge ! Déco, mode, artisanat local. Sélection pointue de créateurs indépendants.",
    category: "Shopping",
    price: "Gratuit",
    location: "Ixelles",
    interests: ["design", "local", "déco"],
    image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&q=80",
    isNew: true,
    website: "https://www.lieudit.be",
    hours: "Mar-Sam: 11:00-19:00",
    rating: 4.4,
  },
  {
    title: "Sunday Market à Tour & Taxis",
    description: "Grand marché food, vintage, design tous les dimanches ! 200 stands, DJ, street food, ambiance festive.",
    category: "Shopping",
    price: "Gratuit",
    location: "Bruxelles - Tour & Taxis",
    interests: ["marché", "food", "vintage"],
    image: "https://images.unsplash.com/photo-1533900298318-6b8da08a523e?w=800&q=80",
    isNew: false,
    website: "https://www.sundaymarket.be",
    hours: "Dim: 10:00-18:00",
    rating: 4.5,
  },
  {
    title: "Atelier Tropicana (Plantes d'Intérieur)",
    description: "Pépinière urbaine hyper cool ! Plantes rares, cactus, terrariums. Conseils d'entretien inclus.",
    category: "Shopping",
    price: "Gratuit",
    location: "Saint-Gilles",
    interests: ["plantes", "déco", "nature"],
    image: "https://images.unsplash.com/photo-1466781783364-36c955e42a7f?w=800&q=80",
    isNew: true,
    website: "https://www.tropicanaplants.be",
    hours: "Mer-Dim: 11:00-19:00",
    rating: 4.7,
  },

  // 👨‍👩‍👧 KIDS & FAMILLE (7 activités)
  {
    title: "Scientastic au Muséum des Sciences Naturelles",
    description: "Musée pour enfants avec dinosaures, espace, océans ! Animations interactives, ateliers le week-end.",
    category: "Famille",
    price: "Payant",
    location: "Bruxelles - Parc Léopold",
    interests: ["enfants", "science", "éducatif"],
    image: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800&q=80",
    isNew: false,
    website: "https://www.naturalsciences.be",
    hours: "Mar-Dim: 10:00-17:00",
    rating: 4.6,
  },
  {
    title: "Récréarium (Plaine de Jeux Indoor)",
    description: "Parc de jeux couvert géant ! Toboggans, trampolines, labyrinthes. Parfait par temps de pluie. 1-12 ans.",
    category: "Famille",
    price: "Payant",
    location: "Woluwe",
    interests: ["enfants", "jeux", "indoor"],
    image: "https://images.unsplash.com/photo-1513616945021-c831cc68c1e8?w=800&q=80",
    isNew: false,
    website: "https://www.recrearium.be",
    hours: "Mer-Dim: 10:00-19:00",
    rating: 4.4,
  },
  {
    title: "Théâtre de Poche (Spectacles Jeunesse)",
    description: "Spectacles pour enfants tous les mercredis et week-ends ! Marionnettes, contes, magie. 3-10 ans.",
    category: "Famille",
    price: "Payant",
    location: "Bruxelles - Centre",
    interests: ["enfants", "théâtre", "spectacle"],
    image: "https://images.unsplash.com/photo-1516307365426-bea591f05011?w=800&q=80",
    isNew: false,
    website: "https://www.poche.be",
    hours: "Mer-Dim: 14:00-16:00",
    rating: 4.5,
  },
  {
    title: "Ferme pour Enfants au Parc Josaphat",
    description: "Mini-ferme gratuite ! Chèvres, lapins, poules, cochons d'Inde. Les enfants peuvent nourrir les animaux.",
    category: "Famille",
    price: "Gratuit",
    location: "Schaerbeek",
    interests: ["enfants", "animaux", "nature"],
    image: "https://images.unsplash.com/photo-1530281700549-e82e7bf110d6?w=800&q=80",
    isNew: false,
    website: "https://www.bruxelles.be/parcs",
    hours: "Mer-Dim: 10:00-17:00",
    rating: 4.3,
  },
  {
    title: "Atelier Cuisine Parent-Enfant",
    description: "Cuisinez ensemble ! Recettes simples et fun. Chaque duo repart avec ses créations. 5-12 ans + 1 adulte.",
    category: "Famille",
    price: "Payant",
    location: "Ixelles",
    interests: ["cuisine", "enfants", "famille"],
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
    isNew: true,
    website: "https://www.cookingkids.be",
    hours: "Sam: 14:00-16:30",
    rating: 4.6,
  },
  {
    title: "Bibliothèque des Enfants",
    description: "Espace lecture gratuit pour enfants ! Milliers de livres, coins lecture cosy, animations contes le mercredi.",
    category: "Famille",
    price: "Gratuit",
    location: "Bruxelles - Centre",
    interests: ["enfants", "lecture", "éducatif"],
    image: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=800&q=80",
    isNew: false,
    website: "https://www.bibliotheque.be",
    hours: "Mer-Sam: 10:00-18:00",
    rating: 4.4,
  },
  {
    title: "Chasse au Trésor en Ville",
    description: "Parcours ludique et éducatif dans Bruxelles ! Énigmes, QR codes, découverte de la ville. App gratuite. Familles.",
    category: "Famille",
    price: "Gratuit",
    location: "Bruxelles - Centre",
    interests: ["enfants", "jeu", "découverte"],
    image: "https://images.unsplash.com/photo-1596490458345-e0a37d1d4d30?w=800&q=80",
    isNew: true,
    website: "https://www.treasurehunt.brussels",
    hours: "Tous les jours",
    rating: 4.5,
  },
];

/**
 * Fonction pour générer les dates futures aléatoires
 */
function getRandomFutureDate(): string {
  const today = new Date();
  const daysToAdd = Math.floor(Math.random() * 60) + 1;
  const futureDate = new Date(today);
  futureDate.setDate(today.getDate() + daysToAdd);
  return futureDate.toISOString().split('T')[0];
}

/**
 * FONCTION PRINCIPALE : Ajouter 50 nouvelles activités dans Firestore
 */
export async function generateMoreActivities() {
  
  try {
    const activitiesRef = collection(db, "activities");
    let count = 0;

    for (const activity of MORE_ACTIVITIES_DATA) {
      const activityData = {
        ...activity,
        date: getRandomFutureDate(),
        createdAt: new Date().toISOString(),
      };

      await addDoc(activitiesRef, activityData);
      count++;
      
      await new Promise(resolve => setTimeout(resolve, 200));
    }

    return { success: true, count };
  } catch (error) {
    console.error("❌ Error generating MORE activities:", error);
    return { success: false, error };
  }
}