import { addDoc, collection, getDocs } from "firebase/firestore";
import { db } from "../firebase_Config";

// 50 VRAIES ACTIVITÉS À FAIRE À BRUXELLES (pas de restos/bars)
const ACTIVITIES_DATA = [
  // 🎳 BOWLING
  {
    title: "Bowling au Crosly (Gare Centrale)",
    description: "Le bowling culte du centre de Bruxelles ! 12 pistes, ambiance vintage. Parfait pour une soirée entre amis.",
    category: "Sport",
    price: "Payant",
    location: "Bruxelles - Gare Centrale",
    interests: ["sport", "fun", "groupe"],
    image: "https://images.unsplash.com/photo-1514313122851-5167c4fca5d6?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    isNew: false,
    website: "https://www.crosly.be",
    hours: "Lun-Dim: 14:00-02:00",
    rating: 3.8,
  },
  {
    title: "Bowling Stone à Wemmel",
    description: "Complexe moderne avec 24 pistes et billard. Ambiance familiale, parfait pour groupes !",
    category: "Sport",
    price: "Payant",
    location: "Wemmel",
    interests: ["sport", "fun", "famille"],
    image: "https://images.unsplash.com/photo-1551500357-f50395bb3f75?q=80&w=1169&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    isNew: false,
    website: "https://www.bowlingstone.be",
    hours: "Lun-Dim: 10:00-00:00",
    rating: 4.2,
  },

  // 🎮 GAMING & ESCAPE
  {
    title: "OutBreak Escape Rooms",
    description: "5 salles d'escape game ultra immersives ! Zombies, prisons, bunker... 60min de frissons en équipe.",
    category: "Gaming",
    price: "Payant",
    location: "Bruxelles - Centre",
    interests: ["énigmes", "groupe", "fun"],
    image: "https://images.unsplash.com/photo-1567789390003-6a956045e378?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    isNew: false,
    website: "https://www.outbreakescaperooms.be",
    hours: "Mar-Dim: 10:00-22:00",
    rating: 4.5,
  },
  {
    title: "Outpost Game Center (BarCraft)",
    description: "Bar gaming avec 50+ consoles et jeux rétro ! Smash Bros, Mario Kart, tournois entre amis.",
    category: "Gaming",
    price: "Payant",
    location: "Ixelles",
    interests: ["gaming", "retrogaming", "compétition"],
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&q=80",
    isNew: false,
    website: "https://www.outpost.be",
    hours: "Mer-Dim: 14:00-23:00",
    rating: 4.3,
  },
  {
    title: "Get-Out Brussels (Escape Game)",
    description: "Escape games avec décors cinématographiques. Braquage, espionnage, horreur... 2-6 joueurs.",
    category: "Gaming",
    price: "Payant",
    location: "Bruxelles - Centre",
    interests: ["énigmes", "groupe", "immersion"],
    image: "https://images.unsplash.com/photo-1463871181391-8550cd89c179?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    isNew: false,
    website: "https://bruxelles.getout.be",
    hours: "Lun-Dim: 13:00-21:00",
    rating: 4.8,
  },
  {
    title: "Virtual Room (VR Escape)",
    description: "Escape game en réalité virtuelle ! Explorez des mondes fantastiques en équipe, expérience incroyable.",
    category: "Gaming",
    price: "Payant",
    location: "Bruxelles - Centre",
    interests: ["VR", "gaming", "innovation"],
    image: "https://images.unsplash.com/photo-1617802690992-15d93263d3a9?w=800&q=80",
    isNew: true,
    website: "https://brussels.virtual-room.com",
    hours: "Mar-Dim: 11:00-21:00",
    rating: 4.7,
  },

  // 🏃 SPORT & AVENTURE
  {
    title: "Climb Up Woluwe (Escalade)",
    description: "Salle d'escalade moderne sur 1500m². Murs jusqu'à 17m, blocs, cours pour tous niveaux.",
    category: "Sport",
    price: "Payant",
    location: "Woluwe-Saint-Pierre",
    interests: ["sport", "escalade", "challenge"],
    image: "https://images.unsplash.com/photo-1696105538782-7815474f28e0?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE3fHx8ZW58MHx8fHx8",
    isNew: false,
    website: "https://brussels-woluwe.climb-up.be",
    hours: "Lun-Ven: 12:00-23:00, Sam-Dim: 10:00-20:00",
    rating: 4.4,
  },
  {
    title: "Arkose Brussels (Escalade)",
    description: "Salle d'escalade urbaine avec bar et espace coworking. Blocs, murs, cours et compétitions.",
    category: "Sport",
    price: "Payant",
    location: "Anderlecht",
    interests: ["sport", "escalade", "convivial"],
    image: "https://images.unsplash.com/photo-1564769662533-4f00a87b4056?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8RXNjYWxhZGV8ZW58MHx8MHx8fDI%3D",
    isNew: false,
    website: "https://arkose.com/salle/bruxelles",
    hours: "Lun-Ven: 07:00-23:00, Sam-Dim: 09:00-20:00",
    rating: 4.5,
  },
  {
    title: "Beta Brussels (Escalade Etterbeek)",
    description: "Salle d'escalade moderne à Etterbeek. Blocs variés, murs de vitesse, ambiance chaleureuse.",
    category: "Sport",
    price: "Payant",
    location: "Etterbeek",
    interests: ["sport", "escalade", "challenge"],
    image: "https://images.unsplash.com/photo-1659666287295-7da26c3f80d4?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8RXNjYWxhZGUlMjBzYWxsZXxlbnwwfHwwfHx8Mg%3D%3D",
    isNew: false,
     website: "https://www.beta.brussels",
    hours: "Lun-Ven: 12:00-23:00, Sam-Dim: 10:00-20:00",
    rating: 4.6,
  },
  {
    title: "Brussels Kart Expo (Karting)",
    description: "Piste de karting indoor de 850m ! Sensations fortes, chrono, parfait pour EVJF/EVG.",
    category: "Sport",
    price: "Payant",
    location: "Anderlecht",
    interests: ["sport", "fun", "adrénaline"],
    image: "https://images.unsplash.com/photo-1628468490086-36cfe5c4fb7d?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8a2FydGluZ3xlbnwwfHwwfHx8Mg%3D%3D",
    isNew: false,
    website: "https://www.brusselskart.be/fr_BE/",
    hours: "Mer-Dim: 14:00-23:00",
    rating: 4.1,
  },
  {
    title: "Laser Game Evolution",
    description: "Arène de laser game futuriste ! 1200m², effets spéciaux, 5 modes de jeu. Jusqu'à 30 joueurs.",
    category: "Sport",
    price: "Payant",
    location: "Jette",
    interests: ["sport", "fun", "compétition"],
    image: "https://images.unsplash.com/photo-1511447333015-45b65e60f6d5?w=800&q=80",
    isNew: false,
    website: "https://www.lasergame-evolution.be",
    hours: "Mer-Dim: 14:00-22:00",
    rating: 4.2,
  },
  {
    title: "Jump XL Trampoline Park",
    description: "Parc de trampolines géant ! Free jump, dodgeball, ninja parcours. Fun garanti pour tous âges.",
    category: "Sport",
    price: "Payant",
    location: "Anderlecht",
    interests: ["sport", "fun", "famille"],
    image: "https://images.unsplash.com/photo-1598296343682-d12ca60fa64b?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fHRyYW1wb2xpbmV8ZW58MHx8MHx8fDI%3D",
    isNew: false,
    website: "https://www.jumpxl.be",
    hours: "Lun-Dim: 10:00-21:00",
    rating: 4.3,
  },
  {
    title: "Run Collectif Brussels Runners",
    description: "Jogging en groupe tous les mardis 19h départ Flagey. 8-12km, rythme modéré, convivial !",
    category: "Sport",
    price: "Gratuit",
    location: "Ixelles - Flagey",
    interests: ["sport", "running", "groupe"],
    image: "https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=800&q=80",
    isNew: false,
    website: "https://www.meetup.com/brussels-runners/",
    hours: "Tous les mardis: 19:00",
    rating: 4.5,
  },


  // 🎨 CULTURE & ART
  {
    title: "Parcours BD (Comic Strip Route)",
    description: "50+ fresques murales géantes à travers Bruxelles ! Tintin, Lucky Luke... Balade street art unique.",
    category: "Culture",
    price: "Gratuit",
    location: "Bruxelles - Centre",
    interests: ["culture", "art", "balade"],
    image: "https://images.unsplash.com/photo-1618519764620-7403abdbdfe9?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8YmR8ZW58MHx8MHx8fDI%3D",
    isNew: false,
     website: "https://www.bruxelles.be/parcours-bd",
    hours: "24/7 - Balade libre",
    rating: 4.6,
    
  },
  {
    title: "MIMA (Musée du Millenium)",
    description: "Musée d'art contemporain et street art. Expos temporaires incroyables, rooftop bar.",
    category: "Culture",
    price: "Payant",
    location: "Molenbeek",
    interests: ["art", "culture", "moderne"],
    image: "https://images.unsplash.com/photo-1496889196885-5ddcec5eef4d?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8bXVzJUMzJUE5ZXxlbnwwfHwwfHx8Mg%3D%3D",
    isNew: true,
    website: "https://www.mimamuseum.eu",
    hours: "Mer-Dim: 12:00-18:00",
    rating: 4.3,
  },
  {
    title: "Atomium & Mini-Europe",
    description: "Visite de l'Atomium (monument iconique) + Mini-Europe avec monuments d'Europe en miniature.",
    category: "Culture",
    price: "Payant",
    location: "Bruxelles - Heysel",
    interests: ["culture", "découverte", "famille"],
    image: "https://images.unsplash.com/photo-1660636721671-07b4894e955d?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8YXRvbWl1bXxlbnwwfHwwfHx8Mg%3D%3D",
    isNew: false,
    website: "https://www.atomium.be",
    hours: "Lun-Dim: 10:00-18:00",
    rating: 4.4,
  },
  {
    title: "Musée Magritte",
    description: "Plus grande collection au monde de Magritte ! Plongez dans l'univers surréaliste du maître belge.",
    category: "Culture",
    price: "Payant",
    location: "Bruxelles - Centre",
    interests: ["art", "culture", "surréalisme"],
    image: "https://images.unsplash.com/photo-1671733082052-87a66c2340b6?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8bWFncml0dGV8ZW58MHx8MHx8fDI%3D",
    isNew: false,
    website: "https://www.musee-magritte-museum.be",
    hours: "Mar-Dim: 10:00-17:00",
    rating: 4.5,
  },
  {
    title: "Théâtre Royal de Toone (Marionnettes)",
    description: "Théâtre de marionnettes traditionnel depuis 1830 ! Spectacles en dialecte bruxellois, unique au monde.",
    category: "Culture",
    price: "Payant",
    location: "Bruxelles - Centre",
    interests: ["culture", "tradition", "théâtre"],
    image: "https://images.unsplash.com/photo-1631462275675-25a353c4f867?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8bWFyaW9ubmV0dGV8ZW58MHx8MHx8fDI%3D",
    isNew: false,
    website: "https://www.toone.be",
    hours: "Représentations: Ven-Sam 20:30",
    rating: 4.2,
  },
  {
    title: "Théâtre Royal du Parc",
    description: "Théâtre historique avec programmation classique et contemporaine. Pièces, comédies, one-man-shows.",
    category: "Culture",
    price: "Payant",
    location: "Bruxelles - Parc Royal",
    interests: ["culture", "théâtre", "spectacle"],
    image: "https://images.unsplash.com/photo-1615414047026-802692414b79?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8dGhlYXRyZXxlbnwwfHwwfHx8Mg%3D%3D",
    isNew: false,
    website: "https://www.theatreduparc.be",
    hours: "Selon programmation",
    rating: 4.3,
  },
  {
    title: "Atelier Graffiti avec CoGraffiti",
    description: "Initiez-vous au street art avec un artiste professionnel ! Bombes et mur légal fournis.",
    category: "Culture",
    price: "Payant",
    location: "Anderlecht",
    interests: ["art", "créativité", "fun"],
    image: "https://images.unsplash.com/photo-1565476599063-a9b93037c7f0?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Z3JhZml0dGl8ZW58MHx8MHx8fDI%3D",
    isNew: true,
    website: "https://www.cograffiti.com",
    hours: "Sur réservation",
    rating: 4.6,
  },

  // 🎬 CINÉMA & SPECTACLES
  {
    title: "Cinéma Vendôme (Ixelles)",
    description: "Cinéma d'art et essai mythique ! Films en VO, ambiance cosy, programmation pointue.",
    category: "Cinéma",
    price: "Payant",
    location: "Ixelles",
    interests: ["cinéma", "culture", "art"],
    image: "https://images.unsplash.com/photo-1485095329183-d0797cdc5676?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8Y2luZW1hfGVufDB8fDB8fHwy",
    isNew: false,
    website: "https://www.cinema-vendome.be",
    hours: "Séances: 14:00-22:00",
    rating: 4.4,
  },
  {
    title: "Kinepolis Brussels",
    description: "Le plus grand complexe de Belgique ! 28 salles dont IMAX Laser, 4DX, Dolby Atmos. Blockbusters et avant-premières.",
    category: "Cinéma",
    price: "Payant",
    location: "Bruxelles - Heysel",
    interests: ["cinéma", "IMAX", "technologie"],
    image: "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Y2luJUMzJUE5bWF8ZW58MHx8MHx8fDI%3D",
    isNew: false,
    website: "https://kinepolis.be/fr/?complex=KBRU&main_section=tous+les+films",
    hours: "Séances: 10:00-23:00",
    rating: 4.2,
  },
  {
    title: "UGC Toison d'Or (Cinéma)",
    description: "Complexe moderne avec 8 salles dont IMAX. Blockbusters et avant-premières, son Dolby Atmos.",
    category: "Cinéma",
    price: "Payant",
    location: "Ixelles",
    interests: ["cinéma", "IMAX", "sortie"],
    image: "https://images.unsplash.com/photo-1668890094751-6986d0ca9dfc?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fGNpbiVDMyVBOW1hfGVufDB8fDB8fHwy",
    isNew: false,
    website: "https://www.ugc.be",
    hours: "Séances: 11:00-23:00",
    rating: 4.1,
  },
  {
    title: "Cinéma en Plein Air au Parc",
    description: "Projections gratuites de films cultes dans le parc en été. Apportez votre couverture !",
    category: "Cinéma",
    price: "Gratuit",
    location: "Bruxelles - Parc du Cinquantenaire",
    interests: ["cinéma", "gratuit", "été"],
    image: "https://www.pexels.com/fr-fr/photo/projection-de-film-en-plein-air-en-foret-35069835/",
    isNew: true,
    website: "https://bruxellesfaitsoncinema.be",
    hours: "Juil-Août: 21:00",
    rating: 4.5,
  },

  // 🎵 MUSIQUE & CONCERTS
  {
    title: "Concert à l'Ancienne Belgique (AB)",
    description: "Salle de concert légendaire ! Tous les grands noms y sont passés. Programmation éclectique.",
    category: "Musique",
    price: "Payant",
    location: "Bruxelles - Centre",
    interests: ["musique", "concert", "sortie"],
    image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8Y29uY2VydHxlbnwwfHwwfHx8Mg%3D%3D",
    isNew : false,
    website: "https://www.abconcerts.be",
    hours: "Selon programmation",
    rating: 4.6,
  },
  {
    title: "Concert à Forest National",
    description: "Salle mythique de 8000 places ! Les plus grandes stars internationales : pop, rock, rap, variété.",
    category: "Musique",
    price: "Payant",
    location: "Forest",
    interests: ["musique", "concert", "grand show"],
    image: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&q=80",
    isNew: false,
    website: "https://www.forest-national.be",
    hours: "Selon programmation",
    rating: 4.3,
  },
  {
    title: "Concert à l'ING Arena",
    description: "Stade de 13 000 places pour les plus gros concerts ! Rihanna, Beyoncé, Coldplay...",
    category: "Musique",
    price: "Payant",
    location: "Anderlecht",
    interests: ["musique", "concert", "stade"],
    image: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800&q=80",
    isNew: false,
     website: "https://ing.arena.brussels",
    hours: "Selon programmation",
    rating: 4.2,
  },
  {
    title: "Concert à La Madeleine",
    description: "Église désacralisée transformée en salle de concert ! Acoustique exceptionnelle, programmation pointue.",
    category: "Musique",
    price: "Payant",
    location: "Bruxelles - Centre",
    interests: ["musique", "concert", "acoustique"],
    image: "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=800&q=80",
    isNew: false,
    website: "https://www.lamadeleine.be",
    hours: "Selon programmation",
    rating: 4.5,
  },
  {
    title: "Botanique (Concerts & Festivals)",
    description: "Centre culturel magnifique avec concerts, festivals et expositions. Terrasse sublime !",
    category: "Musique",
    price: "Payant",
    location: "Bruxelles - Botanique",
    interests: ["culture", "musique", "festival"],
    image: "https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8Y29uY2VydHxlbnwwfHwwfHx8Mg%3D%3D",
    isNew: false,
    website: "https://www.botanique.be",
    hours: "Selon programmation",
    rating: 4.4,
  },
  {
    title: "Jazz au Sounds Jazz Club",
    description: "Club de jazz intimiste avec concerts live tous les soirs. Ambiance feutrée, acoustique parfaite.",
    category: "Musique",
    price: "Payant",
    location: "Ixelles",
    interests: ["musique", "jazz", "concert"],
    image: "https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800&q=80",
    isNew: false,
    website: "https://www.soundsjazzclub.be",
    hours: "Mar-Sam: 20:00-02:00",
    rating: 4.5,
  },
  {
    title: "Karaoké au K-Pub",
    description: "Soirée karaoké avec box privées ! Large choix de chansons françaises et internationales.",
    category: "Musique",
    price: "Payant",
    location: "Bruxelles - Centre",
    interests: ["musique", "fun", "sortie"],
    image: "https://images.unsplash.com/photo-1738156674456-97cdf7793bb7?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8a2FyYW9rZXxlbnwwfHwwfHx8Mg%3D%3D",
    isNew: false,
    website: "https://www.facebook.com/kpubbrussels",
    hours: "Jeu-Sam: 20:00-03:00",
    rating: 4.0,
  },

  // 🌳 NATURE & PARCS
  {
    title: "Bois de la Cambre (Balade & Pique-nique)",
    description: "Poumon vert de Bruxelles ! Lac, pédalos, terrasses... Parfait pour pique-niquer ou faire du sport.",
    category: "Nature",
    price: "Gratuit",
    location: "Ixelles",
    interests: ["nature", "sport", "détente"],
    image: "https://images.unsplash.com/photo-1585938389612-a552a28d6914?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8cGFyY3xlbnwwfHwwfHx8Mg%3D%3D",
    isNew: false,
    website: "https://www.bruxellesenvironnement.be",
    hours: "24/7 - Accès libre",
    rating: 4.5,
  },
  {
    title: "Serres Royales de Laeken",
    description: "Ouvertes 3 semaines par an ! Serres Art Nouveau spectaculaires avec plantes tropicales rares.",
    category: "Nature",
    price: "Gratuit",
    location: "Laeken",
    interests: ["nature", "culture", "unique"],
    image: "https://images.unsplash.com/photo-1506277450472-30e3f3f55129?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8c2VycmV8ZW58MHx8MHx8fDI%3D",
    isNew: false,
     website: "https://www.bruxelles.be/serres-laeken",
    hours: "Avril-Mai uniquement",
    rating: 4.7,
  },
  {
    title: "Parc du Cinquantenaire (Sport & Pique-nique)",
    description: "Parc monumental avec arche triomphale. Idéal pour jogging, pique-nique, frisbee ou badminton !",
    category: "Nature",
    price: "Gratuit",
    location: "Etterbeek",
    interests: ["nature", "sport", "famille"],
    image: "https://images.unsplash.com/photo-1588714477688-cf28a50e94f7?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8cGFyY3xlbnwwfHwwfHx8Mg%3D%3D",
    isNew: false,
    website: "https://www.bruxelles.be",
    hours: "24/7 - Accès libre",
    rating: 4.4,
  },
  {
    title: "Forêt de Soignes (Randonnée)",
    description: "Randonnée guidée de 10km dans la plus grande forêt de Bruxelles. Pique-nique prévu !",
    category: "Nature",
    price: "Gratuit",
    location: "Watermael-Boitsfort",
    interests: ["nature", "sport", "randonnée"],
    image: "https://images.unsplash.com/photo-1440581572325-0bea30075d9d?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGZvcmV0fGVufDB8fDB8fHwy",
    isNew: false,
     website: "https://www.foret-de-soignes.be",
    hours: "24/7 - Accès libre",
    rating: 4.6,
  },
  {
    title: "Paddle sur le Canal",
    description: "Location de paddle boards pour explorer Bruxelles depuis l'eau. Expérience unique et fun !",
    category: "Sport",
    price: "Payant",
    location: "Bruxelles - Canal",
    interests: ["sport", "nature", "original"],
    image: "https://images.unsplash.com/photo-1611012376839-d49a817b86c1?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8cGFkZGxlfGVufDB8fDB8fHwy",
    isNew: true,
    website: "https://www.kayak.brussels",
    hours: "Avr-Sep: 10:00-19:00",
    rating: 4.2,
  },
  {
    title: "Balade Vélo le long du Canal",
    description: "30km de piste cyclable le long du canal. Locations de vélos disponibles, balade facile et agréable.",
    category: "Nature",
    price: "Gratuit",
    location: "Bruxelles - Canal",
    interests: ["nature", "sport", "vélo"],
    image: "https://images.unsplash.com/photo-1571333250630-f0230c320b6d?w=800&q=80",
    isNew: false,
    website: "https://www.villo.be",
    hours: "24/7 - Location vélos",
    rating: 4.0,
  },

  // 🎪 ÉVÉNEMENTS & FESTIVALS
  {
    title: "Marché du Midi (Dimanche)",
    description: "Plus grand marché de Bruxelles ! 450 stands, ambiance multiculturelle, produits du monde entier.",
    category: "Événement",
    price: "Gratuit",
    location: "Bruxelles - Midi",
    interests: ["découverte", "culture", "shopping"],
    image: "https://images.unsplash.com/photo-1487646709898-58d3c6e8d886?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fG1hcmNoJUMzJUE5fGVufDB8fDB8fHwy",
    isNew: false,
website: "https://www.bruxelles.be/marches",
    hours: "Dimanche: 06:00-13:00",
    rating: 4.2,
  },
  {
    title: "Marché aux Puces du Jeu de Balle",
    description: "Marché aux puces quotidien dans les Marolles ! Antiquités, vintage, objets insolites.",
    category: "Événement",
    price: "Gratuit",
    location: "Bruxelles - Marolles",
    interests: ["vintage", "chine", "découverte"],
    image: "https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=800&q=80",
    isNew: false,
     website: "https://www.bruxelles.be",
    hours: "Tous les jours: 07:00-14:00",
    rating: 4.1,
  },
  {
    title: "Fête de la Musique",
    description: "Des centaines de concerts gratuits dans toute la ville ! Du midi à minuit, tous styles musicaux.",
    category: "Événement",
    price: "Gratuit",
    location: "Bruxelles - Partout",
    interests: ["musique", "gratuit", "festival"],
    image: "https://images.unsplash.com/photo-1563841930606-67e2bce48b78?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Y29uY2VydHxlbnwwfHwwfHx8Mg%3D%3D",
    isNew: true,
    website: "https://www.fetedelamusique.be",
    hours: "21 juin: 12:00-00:00",
    rating: 4.6,
  },
  {
    title: "Marché de Noël de Bruxelles",
    description: "Chalets, vin chaud, patinoire et grande roue illuminée. Magie de Noël sur la Grand Place !",
    category: "Événement",
    price: "Gratuit",
    location: "Bruxelles - Grand Place",
    interests: ["Noël", "famille", "féérique"],
    image: "https://images.unsplash.com/photo-1482517967863-00e15c9b44be?w=800&q=80",
    isNew: false,
    website: "https://www.plaisirsdhiver.be",
    hours: "Nov-Jan: 12:00-22:00",
    rating: 4.3,
  },
  {
    title: "Brussels Beer Weekend",
    description: "Le plus grand festival de bière de Belgique. Dégustations, animations, concerts, foodtrucks.",
    category: "Événement",
    price: "Payant",
    location: "Bruxelles - Grand Place",
    interests: ["festival", "découverte", "belgique"],
    image: "https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=800&q=80",
    isNew: false,
    website: "https://www.belgianbrewers.be",
    hours: "Sept: Ven-Dim",
    rating: 4.5,
  },

  // 🎉 SOIRÉES & DANSE
  {
    title: "Bloody Louis (Boîte de Nuit)",
    description: "Club légendaire de Bruxelles ! Hip-hop, R&B, Afrobeats. Ambiance de fou, les meilleurs DJ's.",
    category: "Soirée",
    price: "Payant",
    location: "Bruxelles - Louise",
    interests: ["soirée", "danse", "hip-hop"],
    image: "https://images.unsplash.com/photo-1545128485-c400e7702796?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Ym9pdGUlMjBkZSUyMG51aXR8ZW58MHx8MHx8fDI%3D",
    isNew: false,
    website: "https://www.bloodylouis.be",
    hours: "Jeu-Sam: 23:00-06:00",
    rating: 4.2,
  },
  {
    title: "Le Mirano (Club)",
    description: "Club iconique depuis les années 80 ! Électro, house, techno. Soirées thématiques et DJ internationaux.",
    category: "Soirée",
    price: "Payant",
    location: "Bruxelles - Centre",
    interests: ["soirée", "électro", "danse"],
    image: "https://images.unsplash.com/photo-1687511844598-165c1fc387cc?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Ym8lQzMlQUV0ZSUyMGRlJTIwbnVpdHxlbnwwfHwwfHx8Mg%3D%3D",
    isNew: false,
    website: "https://www.mirano.be",
    hours: "Ven-Sam: 23:00-07:00",
    rating: 4.3,
  },
  {
    title: "Fuse (Club Techno)",
    description: "Temple de la techno à Bruxelles ! Club underground mythique, DJ's internationaux, son exceptionnel.",
    category: "Soirée",
    price: "Payant",
    location: "Bruxelles - Marolles",
    interests: ["soirée", "techno", "underground"],
    image: "https://images.unsplash.com/photo-1574154894072-18ba0d48321b?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8Ym8lQzMlQUV0ZSUyMGRlJTIwbnVpdHxlbnwwfHwwfHx8Mg%3D%3D",
    isNew: false,
    website: "https://www.fuse.be",
    hours: "Sam: 23:00-08:00",
    rating: 4.5,
  },
  {
    title: "C12 (Club Électro)",
    description: "Club électro dans une église ! Architecture unique, électro/house, ambiance spirituelle et festive.",
    category: "Soirée",
    price: "Payant",
    location: "Bruxelles - Centre",
    interests: ["soirée", "électro", "unique"],
    image: "https://images.unsplash.com/photo-1578736641330-3155e606cd40?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8Ym8lQzMlQUV0ZSUyMGRlJTIwbnVpdHxlbnwwfHwwfHx8Mg%3D%3D",
    isNew: true,
    website: "https://www.c12-brussels.com",
    hours: "Ven-Sam: 23:00-06:00",
    rating: 4.6,
  },
  {
    title: "Madame Moustache (Club)",
    description: "Club chic avec plusieurs ambiances ! Électro, house, hip-hop. Terrasse et décor rétro.",
    category: "Soirée",
    price: "Payant",
    location: "Bruxelles - Centre",
    interests: ["soirée", "danse", "chic"],
    image:"https://images.unsplash.com/photo-1544785316-6e58aed68a50?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8Ym8lQzMlQUV0ZSUyMGRlJTIwbnVpdHxlbnwwfHwwfHx8Mg%3D%3D",
    isNew: false,
    website: "https://www.madamemoustache.be",
    hours: "Jeu-Sam: 23:00-05:00",
    rating: 4.1,
  },
  {
    title: "Café d'Anvers Brussels (Club)",
    description: "Succursale du club d'Anvers ! Électro, house, techno. Programmation pointue et son de qualité.",
    category: "Soirée",
    price: "Payant",
    location: "Bruxelles - Centre",
    interests: ["soirée", "électro", "techno"],
    image: "https://images.unsplash.com/photo-1632008649281-0846891f76bd?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8Ym8lQzMlQUV0ZSUyMGRlJTIwbnVpdHxlbnwwfHwwfHx8Mg%3D%3D",
    isNew: false,
    website: "https://www.instagram.com/cafedanvers/?hl=fr",
    hours: "Ven-Sam: 23:00-06:00",
    rating: 4.3,
  },
  {
    title: "You Night Club",
    description: "Grand club moderne avec plusieurs salles ! R&B, hip-hop, house. Ambiance jeune et dynamique.",
    category: "Soirée",
    price: "Payant",
    location: "Bruxelles - Louise",
    interests: ["soirée", "danse", "R&B"],
    image: "https://images.unsplash.com/photo-1672841284521-902007897fe8?w=1200&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fGJvJUMzJUFFdGUlMjBkZSUyMG51aXR8ZW58MHx8MHx8fDI%3D",
    isNew: false,
    website: "https://www.you-nightclub.be",
    hours: "Jeu-Sam: 23:00-06:00",
    rating: 4.0,
  },
  {
    title: "The Cellar (Club)",
    description: "Club underground dans une cave ! Électro, techno, house. Ambiance intimiste et décalée.",
    category: "Soirée",
    price: "Payant",
    location: "Saint-Gilles",
    interests: ["soirée", "électro", "underground"],
    image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&q=80",
    isNew: false,
    website: "https://www.thecellar.brussels",
    hours: "Ven-Sam: 23:00-05:00",
    rating: 4.2,
  },
  {
    title: "Cours de Salsa pour Débutants",
    description: "Initiation à la salsa cubaine tous les jeudis. Pas besoin de partenaire, ambiance fun !",
    category: "Danse",
    price: "Payant",
    location: "Saint-Gilles",
    interests: ["danse", "musique", "apprentissage"],
    image: "https://images.unsplash.com/photo-1504609813442-a8924e83f76e?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8c2Fsc2F8ZW58MHx8MHx8fDI%3D",
    isNew: false,
    website: "https://www.salsabrussels.be",
    hours: "Jeudi: 19:30-21:00",
    rating: 4.4,
  },
  {
    title: "Soirée Salsa au Cartagena",
    description: "Cours de salsa suivi d'une soirée dansante. Ambiance latine, DJ live, tous niveaux !",
    category: "Danse",
    price: "Payant",
    location: "Ixelles",
    interests: ["danse", "musique", "soirée"],
    image: "https://images.unsplash.com/photo-1545959570-a94084071b5d?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8ZGFuc2UlMjBzYWxzYXxlbnwwfHwwfHx8Mg%3D%3D",
    isNew: false,
    website: "https://www.cartagena.be",
    hours: "Ven-Sam: 21:00-03:00",
    rating: 4.3,
  },
  {
    title: "Silent Disco au Parc",
    description: "Soirée casque en plein air ! 3 DJs simultanés, vous choisissez votre ambiance. Expérience unique.",
    category: "Soirée",
    price: "Payant",
    location: "Bruxelles - Bois de la Cambre",
    interests: ["musique", "fun", "original"],
    image: "https://images.unsplash.com/photo-1667355745772-8c6b7990d044?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8c2lsZW50JTIwZGlzY298ZW58MHx8MHx8fDI%3D",
    isNew: true,
    website: "https://www.silentdisco.be",
    hours: "Été: Sam 20:00",
    rating: 4.5,
  },

  // 🎨 ATELIERS CRÉATIFS
  {
    title: "C. Ramic Art Cafe",
    description: "Café-atelier où vous peignez votre propre céramique ! Tasses, assiettes, figurines... Ambiance cosy, thé et café offerts. Parfait pour un après-midi créatif entre amis.",
    category: "Culture",
    price: "Payant",
    location: "Bruxelles - Ixelles",
    interests: ["art", "créativité", "manuel"],
    image: "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=800&q=80",
    isNew: false,
     website: "https://www.cramic.be",
    hours: "Mer-Dim: 14:00-20:00",
    rating: 4.1,
    
  },
  {
    title: "Atelier Peinture & Wine",
    description: "Peignez votre toile en dégustant du vin ! Pas besoin d'expérience, ambiance détendue et fun.",
    category: "Culture",
    price: "Payant",
    location: "Ixelles",
    interests: ["art", "créativité", "convivial"],
    image: "https://images.unsplash.com/photo-1723408778833-75cde5f11d50?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cGFpbnQlMjBhbmQlMjB3aW5lfGVufDB8fDB8fHwy",
    isNew: false,
    website: "https://www.paintandsip.be",
    hours: "Jeu-Sam: 19:00-22:00",
    rating: 4.5,
  },
  {
    title: "Atelier Photo Urbaine",
    description: "Balade photo de 3h dans Bruxelles avec un photographe pro. Conseils techniques et composition.",
    category: "Culture",
    price: "Payant",
    location: "Bruxelles - Centre",
    interests: ["photo", "art", "apprentissage"],
    image: "https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=800&q=80",
    isNew: false,
    website: "https://www.photowalks.be",
    hours: "Sam-Dim: 14:00",
    rating: 4.3,
  },

  // 🎲 SOIRÉES JEUX & QUIZ
  {
    title: "Soirée Quiz au Zebra Bar",
    description: "Quiz culture générale tous les mardis ! Équipes de 4-6 personnes, ambiance fun, prix à gagner.",
    category: "Culture",
    price: "Gratuit",
    location: "Saint-Gilles",
    interests: ["quiz", "fun", "groupe"],
    image: "https://images.unsplash.com/photo-1746635732312-0083b7f9423f?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Z2FtZSUyMG5pZ2h0fGVufDB8fDB8fHwy",
    isNew: false,
    website: "https://www.zebrabar.be",
    hours: "Mardi: 20:00",
    rating: 4.2,
  },
  {
    title: "Soirée Jeux de Société Chez Pif",
    description: "Bibliothèque de 500+ jeux ! Animateurs pour vous guider, ambiance conviviale, snacks disponibles.",
    category: "Gaming",
    price: "Payant",
    location: "Bruxelles - Centre",
    interests: ["jeux", "convivial", "groupe"],
    image:"https://images.unsplash.com/photo-1632501641765-e568d28b0015?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8Ym9hcmQlMjBnYW1lfGVufDB8fDB8fHwy",
    isNew: false,
    website: "https://www.chezpif.be",
    hours: "Mar-Dim: 18:00-23:00",
    rating: 4.4,
  },

  // 🚴 ACTIVITÉS ORIGINALES
  {
    title: "Visite Guidée en Beer Bike",
    description: "Pédalez en groupe sur un vélo-bar ! Tour de la ville en pédalant et en dégustant des bières. Hilarant !",
    category: "Sport",
    price: "Payant",
    location: "Bruxelles - Centre",
    interests: ["fun", "groupe", "original"],
    image: "https://images.unsplash.com/photo-1643790399842-dd0fda77d08e?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8YmVlciUyMGJpa2V8ZW58MHx8MHx8fDI%3D",
    isNew: true,
    website: "https://www.beerbike.be",
    hours: "Ven-Sam: 12:00-22:00",
    rating: 4.7,
  },
];

/**
 * Fonction pour générer les dates futures aléatoires
 */
function getRandomFutureDate(): string {
  const today = new Date();
  const daysToAdd = Math.floor(Math.random() * 60) + 1;
  const futureDate = new Date(today);
  futureDate.setDate(today.getDate() + daysToAdd);
  return futureDate.toISOString().split('T')[0];
}

/**
 * FONCTION PRINCIPALE : Générer et ajouter les 50 activités dans Firestore
 */
export async function generateActivities() {
  console.log("🚀 Starting to generate 50 real Brussels activities...");
  
  try {
    const activitiesRef = collection(db, "activities");
    let count = 0;

    for (const activity of ACTIVITIES_DATA) {
      const activityData = {
        ...activity,
        date: getRandomFutureDate(),
        createdAt: new Date().toISOString(),
      };

      await addDoc(activitiesRef, activityData);
      count++;
      console.log(`✅ Added: ${activity.title} (${count}/${ACTIVITIES_DATA.length})`);
      
      await new Promise(resolve => setTimeout(resolve, 200));
    }

    console.log(`🎉 Successfully generated ${count} activities!`);
    return { success: true, count };
  } catch (error) {
    console.error("❌ Error generating activities:", error);
    return { success: false, error };
  }
}

/**
 * Fonction helper pour appeler depuis un bouton
 */
export async function initializeActivitiesIfNeeded() {
  try {
    const activitiesSnapshot = await getDocs(collection(db, "activities"));
    
    if (activitiesSnapshot.empty) {
      console.log("📊 No activities found, generating...");
      return await generateActivities();
    } else {
      console.log(`ℹ️ ${activitiesSnapshot.size} activities already exist`);
      return { success: true, alreadyExists: true, count: activitiesSnapshot.size };
    }
  } catch (error) {
    console.error("❌ Error checking activities:", error);
    return { success: false, error };
  }
}